### ISSUE TITLE
repo cleanup checklist

### ISSUE THREAD

**Issue by ChristinaLK** [datacarpentry/sql-ecology-lesson#289]
- [x] message maintainers slack about protected branch + styles update
- [x] make an issue about updating from `styles` and tag Francois
- [x] merge all straightforward PRs (no changes to structure or content)
- [x] go through existing issues
- [x] close stale/old issues
- [x] tag remaining issues
- [x] create new (non-redundant) issues from the list below
- [x] make a project (?) for longer-term/larger changes
- [x] tackle any older PRs
- [x] ~update maintainer list~ made issue to update maintainers
- [x] editing CONTRIBUTING/README (??) with how to use tags to contribute

**Comment by ChristinaLK** [comment]
Tagging scheme (right now): 

- `type:bug` for inconsistencies/broken things + `status: need more info` to replicate or `help wanted` to actually fix
- `help wanted` on its own indicates something that's ready for a PR, with `good first issue` should be a simpler PR
- `type:discussion` for ideas that need more feedback from the community (many also tagged w/ `help wanted`)
- `type:enhancement` for more "creative" projects. All of these are currently on the project board, sorted into categories.

**Comment by ChristinaLK** [comment]
Plan a bug BBQ for all the little changes? And get people to contribute to discussion?

**Comment by ChristinaLK** [comment]
Created pinned issue for contribution guidelines.
